language: node_js
node_js:
  - 14

jobs:
  include:
      if: branch = master
      script:
        - echo "I am Parissa"
      install:
        - npm install -g firebase-tools
      after_success:
        - firebase deploy --token $FIREBASE_TOKEN